VerstaTestTask/Models/ErrorViewModel.cs
namespace VerstaTestTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VerstaTestTask/Controllers/DeliveryOrderFormsController.cs
using DatabaseWorker;
using DatabaseWorker.Models;
using Microsoft.AspNetCore.Mvc;

namespace VerstaTestTask.Controllers
{
    public class DeliveryOrderFormsController : Controller
    {
        private readonly IVerstaTestTaskRepository dbRepository;

        public DeliveryOrderFormsController(IVerstaTestTaskRepository dbRepository)
        {
            this.dbRepository = dbRepository;
        }

        // GET: DeliveryOrderForms
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await dbRepository.GetDeliveryOrderFormsAsync());
        }

        // GET: DeliveryOrderForms/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var deliveryOrderForm = await dbRepository.GetDeliveryOrderFormByIdAsync(id);
            if (deliveryOrderForm == null)
            {
                return NotFound();
            }

            return View(deliveryOrderForm);
        }

        // GET: DeliveryOrderForms/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View(new DeliveryOrder()
            {
                Id = await dbRepository.GetIdForNextDeliveryOrder()
            });
        }

        // POST: DeliveryOrderForms/Create
        [HttpPost]
        public async Task<IActionResult> Create(
            [Bind("Id,SenderCity,SenderAddress,RecipientCity,RecipientAddress,CargoWeight,CargoPickupDate")]
            DeliveryOrder deliveryOrderForm)
        {
            if (ModelState.IsValid)
            {
                await dbRepository.AddDeliveryOrderFormsAsync(deliveryOrderForm);

                return RedirectToAction(nameof(Index));
            }

            return View(deliveryOrderForm);
        }

        // GET: DeliveryOrderForms/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var deliveryOrderForm = await dbRepository.GetDeliveryOrderFormByIdAsync(id);
            if (deliveryOrderForm == null)
            {
                return NotFound();
            }

            return View(deliveryOrderForm);
        }

        // POST: DeliveryOrderForms/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,SenderCity,SenderAddress,RecipientCity,RecipientAddress,CargoWeight,CargoPickupDate")]
            DeliveryOrder deliveryOrderForm)
        {
            if (id != deliveryOrderForm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await dbRepository.UpdateDeliveryOrderFormsAsync(deliveryOrderForm);

                return RedirectToAction(nameof(Index));
            }

            return View(deliveryOrderForm);
        }

        // GET: DeliveryOrderForms/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var deliveryOrderForm = await dbRepository.GetDeliveryOrderFormByIdAsync(id);
            if (deliveryOrderForm == null)
            {
                return NotFound();
            }

            return View(deliveryOrderForm);
        }

        // POST: DeliveryOrderForms/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await dbRepository.DeleteDeliveryOrderFormsAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

VerstaTestTask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VerstaTestTask.Models;

namespace VerstaTestTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VerstaTestTask/Views/DeliveryOrderForms/Create.cshtml
@model DatabaseWorker.Models.DeliveryOrder

@{
    ViewData["Title"] = "Create";
}

<h1>Создать новый заказ</h1>

<h4>Форма создания заказа</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <div class="form-group">
                <label asp-for="SenderCity" class="control-label"></label>
                <input asp-for="SenderCity" class="form-control" />
                <span asp-validation-for="SenderCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenderAddress" class="control-label"></label>
                <input asp-for="SenderAddress" class="form-control" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientCity" class="control-label"></label>
                <input asp-for="RecipientCity" class="form-control" />
                <span asp-validation-for="RecipientCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientAddress" class="control-label"></label>
                <input asp-for="RecipientAddress" class="form-control" />
                <span asp-validation-for="RecipientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CargoWeight" class="control-label"></label>
                <input asp-for="CargoWeight" class="form-control" />
                <span asp-validation-for="CargoWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CargoPickupDate" class="control-label"></label>
            <input asp-for="CargoPickupDate" class="form-control" value="@DateTime.Today.AddMinutes(1).ToString("dd-MM-yyyy HH:mm")" />
                <span asp-validation-for="CargoPickupDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать заказ" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VerstaTestTask/Views/DeliveryOrderForms/Delete.cshtml
@model DatabaseWorker.Models.DeliveryOrder

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление заказа</h1>

<h3>Вы уверены?</h3>
<div>
    <h4>Форма создания заказа</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SenderCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SenderCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SenderAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SenderAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipientCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipientAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CargoWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CargoWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CargoPickupDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CargoPickupDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить заказ" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

VerstaTestTask/Views/DeliveryOrderForms/Details.cshtml
@model DatabaseWorker.Models.DeliveryOrder

@{
    ViewData["Title"] = "Details";
}

<h1>Дополнительная информация</h1>

<div>
    <h4>Форма создания заказа</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenderCity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenderCity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenderAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenderAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientCity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecipientCity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecipientAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CargoWeight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CargoWeight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CargoPickupDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CargoPickupDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>

VerstaTestTask/Views/DeliveryOrderForms/Edit.cshtml
@model DatabaseWorker.Models.DeliveryOrder

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактировать заказ</h1>

<h4>Форма создания заказа</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SenderCity" class="control-label"></label>
                <input asp-for="SenderCity" class="form-control" />
                <span asp-validation-for="SenderCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenderAddress" class="control-label"></label>
                <input asp-for="SenderAddress" class="form-control" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientCity" class="control-label"></label>
                <input asp-for="RecipientCity" class="form-control" />
                <span asp-validation-for="RecipientCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientAddress" class="control-label"></label>
                <input asp-for="RecipientAddress" class="form-control" />
                <span asp-validation-for="RecipientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CargoWeight" class="control-label"></label>
                <input asp-for="CargoWeight" class="form-control" />
                <span asp-validation-for="CargoWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CargoPickupDate" class="control-label"></label>
                <input asp-for="CargoPickupDate" class="form-control" />
                <span asp-validation-for="CargoPickupDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить изменения" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VerstaTestTask/Views/DeliveryOrderForms/Index.cshtml
@model IEnumerable<DatabaseWorker.Models.DeliveryOrder>

@{
    ViewData["Title"] = "Index";
}

<h1>Список заказов</h1>

<p>
    <a asp-action="Create">Создать новый заказ</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SenderCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SenderAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecipientCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecipientAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CargoWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CargoPickupDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SenderCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SenderAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipientCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipientAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CargoWeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CargoPickupDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Информация о заказе</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>

VerstaTestTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

VerstaTestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Тестовое Задание Versta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VerstaTestTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="DeliveryOrderForms" asp-action="Index">Тестовое Задание Versta </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryOrderForms" asp-action="Index">Список Заказов</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Тестовое Задание Versta 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>